
["Test Combinde Double"]
	#
	############################################
	#Enable this to see debug messages
	#Added
	#-------------------------------------------
	#Default: 50.0
	#-------------------------------------------
	"Double Test" = 50.0

