#
############################################
#Test One
#-------------------------------------------
#Default: [Arc, Knight]
#-------------------------------------------
"Test List 1" = ["Arc", "Knight"]
#
############################################
#Test Two
#-------------------------------------------
#Default: [Arc, 1]
#-------------------------------------------
"Test List 2" = ["Arc", 1]

